package formularios;


import formularios.MySqlConn;
import formularios.ListaRegistro;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class Registro extends javax.swing.JFrame {
    PreparedStatement ps;
    ArrayList <ListaRegistro> lista = new ArrayList();
    MySqlConn conn;
    static Statement sentencia;
    static ResultSet resultado;
    private int habitacion;
     AudioClip musica=java.applet.Applet.newAudioClip(getClass().getResource("/imagenes/audio.wav"));
    public Registro(MySqlConn conn) {
        this.conn=conn;
        initComponents();
    }
    public Registro() {
        initComponents();
         musica.play();
    }

      
        
  
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextFieldHabitacion = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCiudad = new javax.swing.JTextField();
        jDateChooserIngreso = new com.toedter.calendar.JDateChooser();
        jButtonRegistrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDias = new javax.swing.JTextField();
        jTextFieldPersona = new javax.swing.JTextField();
        jTextFieldSalida = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButtonConsulta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(102, 204, 255));
        jLabel3.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Nombre :");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Numero Habitacion:");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Ciudad De Origen:");

        jLabel6.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Numero de Personas:");

        jLabel7.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("Total Dias:");

        jLabel8.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Fecha Ingreso:");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 153));
        jTextField1.setFont(new java.awt.Font("MingLiU-ExtB", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 153, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("CHECK IN HABITACIONES");

        jTextFieldHabitacion.setBackground(new java.awt.Color(223, 249, 242));
        jTextFieldHabitacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldHabitacion.setForeground(new java.awt.Color(255, 0, 102));

        jTextFieldNombre.setBackground(new java.awt.Color(223, 249, 242));
        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(255, 0, 102));

        jTextFieldCiudad.setBackground(new java.awt.Color(223, 249, 242));
        jTextFieldCiudad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldCiudad.setForeground(new java.awt.Color(255, 0, 102));

        jDateChooserIngreso.setBackground(new java.awt.Color(223, 249, 242));
        jDateChooserIngreso.setForeground(new java.awt.Color(255, 0, 102));
        jDateChooserIngreso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jButtonRegistrar.setBackground(new java.awt.Color(153, 51, 255));
        jButtonRegistrar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(255, 204, 255));
        jButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/checkIn.PNG"))); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flamingo2.PNG"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Sitka Heading", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("¡¡¡PENSANDO EN EL PARAISO DE TUS SUEÑOS!!!!");

        jTextFieldDias.setBackground(new java.awt.Color(223, 249, 242));
        jTextFieldDias.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldDias.setForeground(new java.awt.Color(255, 0, 102));

        jTextFieldPersona.setBackground(new java.awt.Color(223, 249, 242));
        jTextFieldPersona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldPersona.setForeground(new java.awt.Color(255, 0, 102));

        jTextFieldSalida.setEditable(false);
        jTextFieldSalida.setBackground(new java.awt.Color(223, 249, 242));
        jTextFieldSalida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldSalida.setForeground(new java.awt.Color(255, 0, 102));

        jLabel11.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("Fecha Salida:");

        jRadioButton1.setBackground(new java.awt.Color(223, 249, 242));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 0, 102));
        jRadioButton1.setText("1 persona extra");

        jRadioButton2.setBackground(new java.awt.Color(223, 249, 242));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 0, 102));
        jRadioButton2.setText("2 personas extras");

        jButtonConsulta.setBackground(new java.awt.Color(204, 153, 255));
        jButtonConsulta.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/habita.PNG"))); // NOI18N
        jButtonConsulta.setText("Consulta habitacion");
        jButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close all jframe.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tecla.PNG"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/stop.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setText("Cargo por una persona $200");

        jLabel16.setText("Cargo por 2 personas $350");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(jTextField1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jButtonConsulta))
                            .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDias, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                    .addComponent(jRadioButton1))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2)
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsulta))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jDateChooserIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDias, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(30, 30, 30)
                                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13)))
                        .addGap(37, 37, 37))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldCiudad, jTextFieldHabitacion});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        this.conn=new MySqlConn();
        String nom, cd,habi,numpers,dias2,date,sal;
        
        int hab, numper , dias,pex,ext;
        nom= this.jTextFieldNombre.getText();
        habi=this.jTextFieldHabitacion.getText();
        cd=this.jTextFieldCiudad.getText();
        numpers=this.jTextFieldPersona.getText();
        dias2=this.jTextFieldDias.getText();
        hab= Integer.parseInt(habi);
        numper=Integer.parseInt(numpers);
        dias=Integer.parseInt(dias2);
        SimpleDateFormat dFormat= new SimpleDateFormat("dd-MM-yyyy");
        date=dFormat.format(jDateChooserIngreso.getDate());
        if(this.jRadioButton1.isSelected()){
            pex=200;
        
        }else if (this.jRadioButton2.isSelected()){
            pex=350;
           
        }else{
            pex=0;
        }
    
        Calendar aux=this.jDateChooserIngreso.getCalendar();
        aux.add(Calendar.DAY_OF_YEAR,dias);
        this.jTextFieldSalida.setText(dFormat.format(aux.getTime()));

        boolean band;
        String dis="Disponible"; 
                    if(hab>=100 && hab<=129){
                    band=personas(hab,numper);
                    if(band==true){
                        alta(hab,nom,cd,numper,dias,date,pex);
                    }
                    }else{
                    JOptionPane.showMessageDialog(this, "Numero de habitacion no existe, favor de ingresar uno correcto");
                    this.jTextFieldHabitacion.setText("");
                    }
        
    }                                        

    public boolean personas(int hab, int numper){
        String sen="Sencilla"; //2
        String dob="Doble";     //3
        String tri="Triple";    //4
                    String habita="select * from habitaciones where NumeroHab = " + "'"+ hab + "'";
                    this.conn.Consult(habita);
                        try {
                            String tipo = this.conn.rs.getString(1);
                            if(tipo.equals(sen)){
                                if(numper<=2){
                                    return true;
                                }else{
                                    JOptionPane.showMessageDialog(this, "Habitacion seleccionada solo admite un max de 2 personas");
                                    this.jTextFieldPersona.setText("");
                                    return false;
                                }
                            }
                            if(tipo.equals(dob)){
                                    if(numper<=3){
                                    return true;
                                    }else{
                                    JOptionPane.showMessageDialog(this, "Habitacion seleccionada solo admite un max de 3 personas");
                                    this.jTextFieldPersona.setText("");
                                    return false;
                                }
                            }
                            if(tipo.equals(tri)){
                                if(numper<=4){
                                    return true;
                                    }else{
                                    JOptionPane.showMessageDialog(this, "Habitacion seleccionada solo admite un max de 4 personas");
                                    this.jTextFieldPersona.setText("");
                                    return false;
                                }
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        return false;
    }
    public void alta(int hab,String nom,String cd,int numper,int dias,String date,int pex){
                        String dis="Disponible";
                        String ocu="Ocupada";
                        String habita="select * from habitaciones where NumeroHab = " + "'"+ hab + "'";
                        this.conn.Consult(habita);
                        try {
                        String dispo=this.conn.rs.getString(5);
                        String tipo=this.conn.rs.getString(1);
                        String pers=this.conn.rs.getString(4);
                        String  piso=this.conn.rs.getString(2);
                        if(dispo.equals(dis)){
                                    ListaRegistro obj;
                                    obj = new ListaRegistro(nom,hab,cd,numper,dias,date,pex);
                                    lista.add(obj);
                                    for (int i = 0; i < lista.size(); i++){
                                    String parte1="Insert into registros(nombre, habitacion, ciudad, personas, dias, fecha, Pextra) VALUES (";
                                    String parte2="'"+lista.get(i).getNombre()+"','"+lista.get(i).getHabitacion()+"','"+lista.get(i).getCiudad()+"','"+lista.get(i).getNumper()+"','"+lista.get(i).getDias()+"','"+lista.get(i).getFecha()+"','"+lista.get(i).getPex()+"')";
                                    String query= parte1 + parte2;
                                    int j=this.conn.Update(query);
                                    String q="UPDATE habitaciones SET Disponibilidad='"+ocu+"' WHERE NumeroHab='"+hab+"'";
                                    int x=this.conn.Update(q);
                                    if(j>0 && x>0){
                                        JOptionPane.showMessageDialog(this, "Habitacion registrada");
                                        JOptionPane.showMessageDialog(this, "Disponibilidad actualizada");
                                        Recibo abrir= new Recibo();
                                        abrir.setVisible(true);
                                        Recibo.jTextFieldnom.setText(nom);
                                        Recibo.jTextFieldCiu.setText(cd);   
                                        Recibo.jTextFieldHab.setText(this.jTextFieldHabitacion.getText()); 
                                        Recibo.jTextFieldIng.setText(date);
                                        int ext;
                                        if(this.jRadioButton1.isSelected())
                                                  ext=1;
                                         else if (this.jRadioButton2.isSelected())
                                                   ext=2;
                                         else 
                                                   ext=0;
            
        
                                        String extra=String.valueOf(ext);
                                        Recibo.jTextFieldExt.setText(extra);
                                        Recibo.jTextFieldPiso.setText(piso);
                                        Recibo.jTextFieldTipo.setText(tipo);
                                        Recibo.jTextFieldlim.setText(pers);
                                        int tot=numper+ext;
                                        String total=String.valueOf(tot);
                                        Recibo.jTextFieldOcu.setText(total);
                                        
                                         SimpleDateFormat dFormat= new SimpleDateFormat("dd-MM-yyyy");
                                         Calendar aux=this.jDateChooserIngreso.getCalendar();
                                         aux.add(Calendar.DAY_OF_YEAR,dias);
                                         Recibo.jTextFieldSal.setText(dFormat.format(aux.getTime()));
                                        
                                       
                                        this.jTextFieldNombre.setText("");
                                        this.jTextFieldHabitacion.setText("");
                                        this.jTextFieldCiudad.setText("");
                                        this.jTextFieldPersona.setText("");
                                        this.jTextFieldDias.setText("");
                                        this.jTextFieldSalida.setText("");
                                        this.buttonGroup1.clearSelection();//limpia botones 
                                        this.jDateChooserIngreso.setCalendar(null);
                                    }
                                    }
                        }else{
                            JOptionPane.showMessageDialog(this, "Numero de habitacion esta ocupada, favor de ingresar otra");
                            this.jTextFieldHabitacion.setText("");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Habitacion c1= new Habitacion();
        c1.setVisible(true);
    }//GEN-LAST:event_jButtonConsultaActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        musica.stop();
         this.setVisible(false);
        MenuSistema ms= new MenuSistema();
        ms.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        musica.play();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        musica.stop();
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonConsulta;
    private javax.swing.JButton jButtonRegistrar;
    private com.toedter.calendar.JDateChooser jDateChooserIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldDias;
    private javax.swing.JTextField jTextFieldHabitacion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPersona;
    public static javax.swing.JTextField jTextFieldSalida;
    // End of variables declaration//GEN-END:variables
}
