/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import formularios.MySqlConn;
import formularios.ListaRegistro;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Salida extends javax.swing.JFrame {

   PreparedStatement ps;
    ArrayList <ListaRegistro> lista = new ArrayList();
    MySqlConn conn;
    static Statement sentencia;
    static ResultSet resultado;
      AudioClip musica=java.applet.Applet.newAudioClip(getClass().getResource("/imagenes/audio.wav"));
    public Salida(MySqlConn conn) {
        this.conn=conn;
        initComponents();
    }
    public Salida() {
        initComponents();
        musica.play();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldHab = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldBar = new javax.swing.JTextField();
        jTextFieldNiñera = new javax.swing.JTextField();
        jTextFieldSpa = new javax.swing.JTextField();
        jTextFieldTintoreria = new javax.swing.JTextField();
        jTextFieldCuarto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flamingo2.PNG"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Sitka Heading", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("¡¡¡PENSANDO EN EL PARAISO DE TUS SUEÑOS!!!!");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 153));
        jTextField1.setFont(new java.awt.Font("MingLiU-ExtB", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 153, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("CHECK OUT HABITACIONES");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Numero Habitacion:");

        jTextFieldHab.setBackground(new java.awt.Color(223, 249, 242));
        jTextFieldHab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldHab.setForeground(new java.awt.Color(255, 0, 102));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(9, 91, 14));
        jTextField2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 255, 204));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("CARGOS EXTRA: ");

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(195, 1, 157));
        jLabel2.setText("Servicio Bar:");

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(195, 1, 157));
        jLabel3.setText("Servicio Tintoreria:");

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(195, 1, 157));
        jLabel5.setText("Servicio Spa:");

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(195, 1, 157));
        jLabel6.setText("Servicio Niñera:");

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(195, 1, 157));
        jLabel7.setText("Servicio al cuarto:");

        jTextFieldBar.setBackground(new java.awt.Color(204, 204, 255));
        jTextFieldBar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jTextFieldBar.setForeground(new java.awt.Color(0, 51, 153));

        jTextFieldNiñera.setBackground(new java.awt.Color(204, 204, 255));
        jTextFieldNiñera.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jTextFieldNiñera.setForeground(new java.awt.Color(0, 51, 153));

        jTextFieldSpa.setBackground(new java.awt.Color(204, 204, 255));
        jTextFieldSpa.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jTextFieldSpa.setForeground(new java.awt.Color(0, 51, 153));

        jTextFieldTintoreria.setBackground(new java.awt.Color(204, 204, 255));
        jTextFieldTintoreria.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jTextFieldTintoreria.setForeground(new java.awt.Color(0, 51, 153));

        jTextFieldCuarto.setBackground(new java.awt.Color(204, 204, 255));
        jTextFieldCuarto.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jTextFieldCuarto.setForeground(new java.awt.Color(0, 51, 153));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Perpetua", 2, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/checkout.PNG"))); // NOI18N
        jButton1.setText("Check Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close all jframe.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tecla.PNG"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/stop.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTextField2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldHab, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTintoreria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNiñera, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldHab, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTintoreria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNiñera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dispo="Disponible",nombre="",cd="",ingreso="",ocupantes="",tipo="",dias="",dis="",preciohab="",piso="",ext="";
        int total=0;
        this.conn=new MySqlConn();
        String habi= this.jTextFieldHab.getText().trim();
        int hab= Integer.parseInt(habi);
        String huesped="select * from registros where habitacion = " + "'"+ hab + "'";
        this.conn.Consult(huesped);
        try {
            nombre=this.conn.rs.getString(1);
            cd=this.conn.rs.getString(3);
            ingreso=this.conn.rs.getString(6);
            ocupantes=this.conn.rs.getString(4);
            dias=this.conn.rs.getString(5);
             ext=this.conn.rs.getString(7);
        } catch (SQLException ex) {
            Logger.getLogger(Salida.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String habita="select * from habitaciones where NumeroHab = " + "'"+ hab + "'";
        this.conn.Consult(habita);
        try {
            dis = this.conn.rs.getString(5);
            tipo=this.conn.rs.getString(1);
            preciohab=this.conn.rs.getString(6);
            piso=this.conn.rs.getString(2);
            if (dis.equals(dispo)){
            JOptionPane.showMessageDialog(this, "Habitacion vacia");
            this.jTextFieldHab.setText("");
            }else{
            String query="delete from registros where habitacion ="+"'"+hab+"'";
            int j=this.conn.Update(query);
            String q="UPDATE habitaciones SET Disponibilidad='"+dispo+"' WHERE NumeroHab='"+hab+"'";
            int x=this.conn.Update(q);
            if(j>0 && x>0){
                JOptionPane.showMessageDialog(this, "Baja realizada");
                JOptionPane.showMessageDialog(this, "Disponibilidad actualizada");
            }
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Salida.class.getName()).log(Level.SEVERE, null, ex);
        }
        String serviciocto= this.jTextFieldCuarto.getText().trim();
        String bar=this.jTextFieldBar.getText().trim();
        String tinto=this.jTextFieldTintoreria.getText().trim();
        String ninera=this.jTextFieldNiñera.getText().trim();
        String spa=this.jTextFieldSpa.getText().trim();
        int sercto= Integer.parseInt(serviciocto);
        int serbar= Integer.parseInt(bar);
        int sertinto= Integer.parseInt(tinto);
        int serninera= Integer.parseInt(ninera);
        int serspa= Integer.parseInt(spa);
        int precioh=Integer.parseInt(preciohab);
        int precioext=Integer.parseInt(ext);
        int dd=Integer.parseInt(dias);
        total= sercto+serbar+sertinto+serninera+serspa+(precioh*dd)+precioext;
//         String parte1= "insert into ingresos (Ganancias) VALUES (";
//        String parte2="'"+total+"')";
//        String query = parte1 + parte2;
//        
//        int j=this.conn.Update(query);
          
        
        try {
            
            //Creacion del PDF
            // Se crea el documento
            Document documento = new Document();
            
            // Se crea el OutputStream para el fichero donde queremos dejar el pdf.
            FileOutputStream ficheroPdf = null;
            try {
                ficheroPdf = new FileOutputStream("Recibo.pdf");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Salida.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
           PdfWriter pdf = PdfWriter.getInstance(documento,ficheroPdf);
            
            // Se abre el documento.
            documento.open();
            
            //Colocar logo      
        try
        {
        	Image logo1= Image.getInstance("logo.PNG");
                logo1.scaleToFit(200, 200);
              
                logo1.setAlignment(Chunk.ALIGN_BOTTOM);
             
              
                documento.add(logo1);
        }catch ( Exception e )
        {
            e.printStackTrace();
        }
            
             
 //agregar parrafos existen diferente formas se presenta algunas de ellas            
Font uni = new Font(Font.FontFamily.TIMES_ROMAN,13, Font.BOLDITALIC, BaseColor.MAGENTA);
Chunk uniText = new Chunk("            HOTEL FLAMINGO CANCUN RESORT      ", uni);
Paragraph p1 = new Paragraph(uniText);
documento.add(p1);
//otra forma 
String centro="¡¡¡PENSANDO EN EL PARAISO DE TUS SUEÑOS!!!!   ";
Font cien= new Font(Font.FontFamily.TIMES_ROMAN,13, Font.BOLDITALIC, BaseColor.CYAN);
Chunk cienText = new Chunk(centro, cien);
Paragraph p2 = new Paragraph(cienText);
documento.add(p2);

Font dep = new Font(Font.FontFamily.TIMES_ROMAN,13, Font.BOLDITALIC, BaseColor.BLUE);
Chunk depText = new Chunk("Boulevard Kukulkán 11, Cancún, Quintana Roo ", dep);
Paragraph p3 = new Paragraph(depText);
documento.add(p3);

Font de = new Font(Font.FontFamily.TIMES_ROMAN,13, Font.BOLDITALIC, BaseColor.BLUE);
Chunk deText = new Chunk("     flamingo@flamingocancunresort.com.mx   ", de);
Paragraph p19 = new Paragraph(deText);
documento.add(p19);

Font d = new Font(Font.FontFamily.TIMES_ROMAN,13, Font.BOLDITALIC, BaseColor.BLUE);
Chunk dText = new Chunk("        +52(998)848.88.77        ", d);
Paragraph p13 = new Paragraph(dText);
documento.add(p13);
Date date =new Date();
DateFormat dateFormat= new SimpleDateFormat("dd/MM/yyyy");
Paragraph  p4= new Paragraph (dateFormat.format(date));
            
                p4.setAlignment(Chunk.ALIGN_RIGHT);
                
                documento.add(p4);

       documento.add(new Paragraph(" "));
            
      Recibo abrir= new Recibo();
      abrir.setVisible(true);
      
      
       
       documento.add(new Paragraph(" "));
       documento.add(new Paragraph("Nombre del huésped: "+nombre));
       documento.add(new Paragraph("Ciudad de Origen: "+cd));
       documento.add(new Paragraph("Fecha de ingreso: "+ingreso));
       documento.add(new Paragraph("Fecha de salida: "+Recibo.jTextFieldSal.getText()));
       documento.add(new Paragraph("Tipo de habitacion: "+tipo));
       documento.add(new Paragraph("Costo Habitacion: "+precioh));
       documento.add(new Paragraph("Dias que se quedo en el hotel: "+dias));
       documento.add(new Paragraph("Total a pagar sin cargos extra: "+precioh));
       documento.add(new Paragraph("Total a pagar con cargos extra: "+total));
       documento.add(new Paragraph("Lista de cargos extra : "));
       documento.add(new Paragraph("Costo persona extra: "+precioext));
       documento.add(new Paragraph("Servicio al cuarto: "+sercto));
       documento.add(new Paragraph("Servicio de bar: "+serbar));
       documento.add(new Paragraph("Servicio de bar: "+serspa));
       documento.add(new Paragraph("Servicio tintoreria: "+sertinto));
       documento.add(new Paragraph("Servicio de niñera: "+serninera));
       
       documento.add(new Paragraph(" "));
       documento.add(new Paragraph(" "));
       
       
        try
        {
        	Image firma = Image.getInstance("firma.png");
                firma.scaleToFit(100, 100);
                firma.setAlignment(Chunk.ALIGN_CENTER);
                documento.add(firma);
        }catch ( Exception e )
        {
            e.printStackTrace();
        }
        
       String linea=" ---------------------------  ";
       Paragraph plin =new Paragraph (linea);
       plin.setAlignment(Chunk.ALIGN_CENTER);
       documento.add(plin);
       
       String Gerente="      Lenin Moreno Gárces  ";
       Paragraph pdir =new Paragraph (Gerente);
       pdir.setAlignment(Chunk.ALIGN_CENTER);
       documento.add(pdir);
       
       String cargo=" Director General del Hotel  ";
       Paragraph pcargo =new Paragraph (cargo);
       pcargo.setAlignment(Chunk.ALIGN_CENTER);
       documento.add(pcargo);
       
       String despedida="  ¡¡¡¡Vuelve pronto¡¡¡¡¡  ";
       Paragraph pdes =new Paragraph (despedida);
       pdes.setAlignment(Chunk.ALIGN_CENTER);
       documento.add(pdes);
          
        documento.close();
        } catch (DocumentException ex) {
            Logger.getLogger(Salida.class.getName()).log(Level.SEVERE, null, ex);
        }
          Recibo abrir= new Recibo();
      
        abrir.setVisible(false);
        
        this.jTextFieldHab.setText("");
        this.jTextFieldCuarto.setText("");
        this.jTextFieldBar.setText("");
        this.jTextFieldTintoreria.setText("");
        this.jTextFieldNiñera.setText("");
        this.jTextFieldSpa.setText("");
                                        
        
        
        //mostrar.setText("Nombre: "+nombre+'\n'+"Ciudad Origen: "+cd+'\n'+"Fecha ingreso: "+ingreso+'\n'+"Numero Habitacion: "+hab+"   piso: "+piso+'\n'+"Tipo habitacion: "+tipo+'\n'+"Total de ocupantes "+ocupantes+'\n'+"Total a pagar (Incluido precio habitacion y cargos extras): "+total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        musica.stop();
         this.setVisible(false);
        MenuSistema ms= new MenuSistema();
        ms.setVisible(true);
                                
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        musica.play();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        musica.stop();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldBar;
    private javax.swing.JTextField jTextFieldCuarto;
    private javax.swing.JTextField jTextFieldHab;
    private javax.swing.JTextField jTextFieldNiñera;
    private javax.swing.JTextField jTextFieldSpa;
    private javax.swing.JTextField jTextFieldTintoreria;
    // End of variables declaration//GEN-END:variables

}
